swipe:
        3:
                left:
                        command: 'xdotool key ctrl+super+Left'
                right:
                        command: 'xdotool key ctrl+super+Right'
                down:
                        command: 'xdotool key alt+shift+Tab'  
                        threshold: 0.5
                        interval: 0.5
                up:
                        command: 'xdotool key ctrl+F10'
pinch:
        2:
                in:
                        command: 'xdotool key ctrl+plus'
                        threshold: 0.1

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
