swipe:
        3:
                right:
                        command: 'xdotool key ctrl+super+Left'
                left:
                        command: 'xdotool key ctrl+super+Right'
                down:
                        command: 'xdotool key ctrl+F8'
                up:
                        command: 'xdotool key alt+super+Right'  
                        threshold: 0.1
                        interval: 0.3
pinch:
        2:
                in:
                        command: 'xdotool key ctrl+plus'
                        threshold: 0.1
                        interval: 0.1
                out:
                        command: 'xdotool key ctrl+minus'
                        threshold: 0.1
                        interval: 0.1
        3:
                in:
                        command: 'xdotool key ctrl+F9'
                out:
                        command: 'xdotool key ctrl+F9'


threshold:
  swipe: 0.5
  pinch: 0.5

interval:
  swipe: 0.5
  pinch: 0.5
